class ResepMenu {
  String name;
  String star;
  String time;
  String category;
  String author;
  String servings;
  List<String> ingredients;
  List<String> instructions;
  String imageAsset;
  bool saved;

  ResepMenu({
    required this.name,
    required this.star,
    required this.time,
    required this.category,
    required this.author,
    required this.servings,
    required this.ingredients,
    required this.instructions,
    required this.imageAsset,
    required this.saved,
  });
}

var resepmenuList = [
  ResepMenu(
    name: 'Soto Ayam Jawa',
    star: '4.8/5 ',
    time: '1 jam',
    category: 'Lauk',
    author: 'Odilia WS',
    servings: '2',
    ingredients: [
      '1/2 ekor ayam kampung',
      '2 liter air',
      '2 batang serai, memarkan',
      '3 cm lengkuas, memarkan',
      '3 lembar daun jeruk',
      '2 lembar daun salam',
      '3 sdm minyak sayur',
      '1 sdt gula pasir',
      '2 sdm kaldu ayam bubuk',
      '2 sdt garam',
      '5 siung bawang putih',
      '3 butir kemiri',
      '3 butir bawang merah',
      '1 sdt merica butiran',
      '1 cm jahe',
      'kol, iris halus',
      'Suun, seduh air panas, tiriskan',
      'Bawang putih goreng',
      'Sambal rawit',
      'Kecap manis',
      'Jeruk nipis',
    ],
    instructions: [
      'Potong ayam menjadi 4 bagian. Cuci bersih, tiriskan.',
      'Didihkan air lalu rebus ayam dengan api kecil hingga kuahnya berkurang.',
      'Tumis Bumbu Halus hingga matang dan harum.',
      'Tambahkan daun salam, serai, daun jeruk, lengkuas, aduk rata lalu masukkan ke dalam rebusan ayam.',
      'Tambahkan kaldu bubuk, gula dan garam.',
      'Rebus dengan api kecil hingga ayam lunak. Matikan api.',
      'Tiriskan ayam, suwir halus dagingnya. Sisihkan.',
      'Taruh suun dan kol dalam mangkuk. Beri suwiran ayam lalu guyur kaldu panas dan sajikan dengan taburan bawang putih goreng, sambal dan kecap manis serta jeruk nipis.',
    ],
    imageAsset: 'images/menu/menu1.jpeg',
    saved: false,
  ),
  ResepMenu(
    name: 'Gado-Gado',
    star: '4.8/5',
    time: '1 hour',
    category: 'Lauk',
    author: 'Shutterstock.com',
    servings: '4',
    ingredients: [
      '150 gram kubis diiris-iris kecil',
      '175 gram bayam',
      '200 gram mentimun diiris-iris kecil',
      '175 gram tauge',
      '300 gram kentang rebus diiris dadu',
      '200 gram kacang panjang',
      '300 gram tahu kuning digoreng dan diiris dadu',
      'Telur rebus dibelah menjadi dua',
      'Kerupuk dan emping',
      'Bawang goreng',
      '4 buah cabe rawit',
      '4 buah cabe merah',
      '4 sdt gula merah',
      '1 sdt terasi bakar',
      '1,5 sdm air asam jawa',
      '2 sdt garam',
      '175 gram kacang tanah ditumbuk halus',
      '175 gram kacang kenari ditumbuk halus',
      'Kecap manis',
      '750 ml air',
    ],
    instructions: [
      'Rebus semua sayuran sampai lunak lalu tiriskan.',
      'Haluskan cabe merah, garam, cabe rawit dan juga terasi hingga halus.',
      'Masukkan kacang tanah dan kacang kenari.',
      'Tambahkan air asam, kecap, air dan gula merah.',
      'Aduk rata lalu masak di atas wajan hingga mendidih.',
      'Biarkan dingin lalu siap disajikan dengan lainnya.',
      'Ambil piring lalu tambahkan sayuran dan kentang.',
      'Lalu masukkan juga tahu dan telur.',
      'Tuangi saus kacang lalu taburi bawang goreng dan emping goreng.',
    ],
    imageAsset: 'images/menu/menu2.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Sop Buntut',
    star: '4.9/5',
    time: '1 hour',
    category: 'Lauk',
    author: 'Dreamstime.com',
    servings: '4',
    ingredients: [
      '1 kg buntut sapi dipotongi',
      '3 buah wortel dipotongi',
      '2 buah kentang dipotongi',
      '2 batang daun bawang dipotongi',
      '1 ikat kecil seledri disimpulkan',
      '1 buah tomat dipotongi',
      '1 buah pala dipecahkan dan haluskan',
      '4 butir cengkeh',
      '2 butir bunga lawang atau pekak',
      '4 cm kayu manis',
      '3 butir kapulaga',
      '1.5 sdm garam',
      '2 sdt gula pasir',
      '2 sdm minyak',
      '2 liter air',
      '7 siung bawang merah',
      '5 siung bawang putih',
      '1/2 sdt merica',
    ],
    instructions: [
      'Panaskan air lalu masak hingga mendidih.',
      'Masukkan buntut sapi lalu rebus sampai berbusa dan buang airnya.',
      'Didihkan air baru lalu masukkan buntut dan rebus sampai lunak',
      'Panaskan minyak dan tumis bunbu halus hingga wangi dan matang.',
      'Masukkan tumisan dalam panci rebusan buntut.',
      'Tambahkan wortel dan kentang lalu masak pakai api kecil sampai mendidih.',
      'Bubuhi garam dan cengkeh lalu masukkan bunga lawang, gula dan kayu manis.',
      'Tambahkan juga kapulaga dan pala lalu tes rasanya.',
      'Masukkan seledri lalu masak sampai buntut empuk dan bumbunya meresap.',
      'Masukkan daun bawang dan irisan tomat lalu angkat dan sajikan.',
    ],
    imageAsset: 'images/menu/menu3.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Tempe Mendoan',
    star: '4.7/5',
    time: '20 minutes',
    category: 'Dessert',
    author: 'Shutterstock.com',
    servings: '4',
    ingredients: [
      '1 papan tempe, iris tipis',
      '2 sdm tepung terigu',
      '2 sdm tepung beras',
      '1 sdm tepung tapioka',
      '2 batang daun bawang, iris tipis',
      '2 lembar daun jeruk, buang punggung daunnya, iris tipis',
    ],
    instructions: [
      'Haluskan bumbu yang terdiri dari bawang putih, bawang merah, kunyit, dan ketumbar lalu campur bumbu halus dengan terigu dan tepung beras.',
      'Masukkan juga tapioka, irisan daun bawang dan daun jeruk.',
      'Gulingkan tempe pada adonan lalu goreng sampai matang.',
    ],
    imageAsset: 'images/menu/menu4.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Martabak Telur',
    star: '4.7/5',
    time: '0.5 hour',
    category: 'Dessert',
    author: 'Lestarisahidin',
    servings: '4',
    ingredients: [
      '2 sendok makan telur, kocok lepas',
      '1 sendok makan minyak',
      '100 gram tepung terigu',
      'Air secukupnya',
      'Garam secukupnya',
      '6 sendok makan irisan bawang bombay',
      '300 gram daging giling, sesuai selera',
      '4 siung bawang putih, haluskan.',
      '6 butir telur ayam',
      '1 sendok bubuk kari',
      'Merica bubuk secukupnya',
      '1 batang daun bawang, iris-iris',
      'Garam seperlunya',
    ],
    instructions: [
      'Ambil wadah. Masukkan tepung terigu, minyak, telur, dan garam ke dalamnya. Aduk dan campurkan secara merata.',
      'Tambahkan pula air ke dalamnya sedikit demi sedikit dan uleni adonan hingga kalis.',
      'Ambil adonan menjadi 2 bagian, lalu bulatkan.',
      'Siapkan wadah, tuangkan minyak goreng ke dalamnya, lalu rendam adonan di dalamnya.',
      'Diamkan adonan selama 1-2 jam.',
      'Siapkan wajan, letakkan di atas kompor, tuangkan minyak, nyalakan kompor, dan panaskan minyak.',
      'Masukkan bawang bombay dan bawang putih, tumis hingga mengeluarkan aroma harum.',
      'Tambahkan bubuk kari, irisan daun bawang, daging giling, merica, dan garam.',
      'Aduk semuanya hingga tercampur merata dan matang, lalu angkat dan sisihkan. Pisahkan jadi 2 bagian.',
      'Kocok telur, lalu tuangkan ke wajan, dan masak dengan bentuk orak-arik setengah matang. Jika sudah matang, maka angkat, sisihkan, dan pisahkan jadi 2 bagian.',
      'Ambil 1 adonan kulit martabak, pipihkan dan bentangkan hingga lebar dan tipis.',
      'Isi kulit martabak dengan isian martabak tadi. Ulangi proses ini hingga adonan dan isian habis.',
      'ipat dan tutup adonan menjadi bentuk amplop.',
      'Siapkan wajan, tuangkan minyak, panaskan.',
      'Masukkan martabak, goreng hingga coklat keemasan dan matang.',
      'Jika sudah, maka angkat dan sajikan Martabak Telur Spesial selagi hangat.',
    ],
    imageAsset: 'images/menu/menu5.jpg',
    saved: false,
  ),
];

var resepMainFood = [
  ResepMenu(
    name: 'Nasi Liwet',
    star: '4.2/5 ',
    time: '0.75 jam',
    category: 'Makanan Utama, Indonesia',
    author: 'Kummelissa',
    servings: '4',
    ingredients: [
      '500 gram beras',
      '500 ml santan',
      '2 lembar daun salam',
      '3 lembar daun pandan',
      '2 sdm air jeruk nipis',
      'Gula dan garam',
      '500 gram ayam kampung',
      '2 ruas lengkuas',
      '2 ruas kunyit',
      '1 ruas jahe',
      '3 siung bawang merah',
      '2 siung bawang putih',
      '2 butir kemiri',
      'Minyak goreng',
    ],
    instructions: [
      'Cuci beras lalu masukkan ke dalam rice cooker beserta dengan santan, air jeruk nipis, dan daun pandan. Tunggu hingga matang.',
      'Sisihkan terlebih dahulu nasi yang sudah matang',
      'Panaskan minyak, lalu tumis bahan-bahan seperti bawang, kemiri, gula, garam, kunyit, jahe, lengkuas dan daun salam. Aduk sampai rata dan mengeluarkan aroma harum.',
      'Setelah tumisan matang, masukkan ayam dan masak sampai matang.',
      'Lalu, suwir-suwir ayam yang sudah dimasak dan masukkan ke dalam nasi yang sudah matang tadi.',
      'Nasi liwet Solo siap disajikan.',
    ],
    imageAsset: 'images/main/main1.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Rawon',
    star: '4.4/5',
    time: '1 hour',
    category: 'Makanan Utama, Indonesia',
    author: 'Merdeka.com',
    servings: '4',
    ingredients: [
      '500 gram daging sandung lamur',
      '2 batang serai, memarkan',
      '5 lembar daun jeruk',
      '1 ruas lengkuas, memarkan',
      'Air secukupnya',
      '6 siung bawang merah',
      '3 siung bawang putih',
      '7 buah kluwek, keruk isinya',
      '1 sdt ketumbar',
      '3 butir kemiri, sangrai',
      '1 ruas kunyit, bakar',
      'Garam secukupnya',
      'Gula secukupnya',
      'Kaldu bubuk secukupnya',
      'Kecambah',
      'Telur asin',
      'Sambal terasi',
    ],
    instructions: [
      'Tumis bumbu halus, lengkuas, serai dan daun jeruk hingga harum dan matang.',
      'Kemudian masukkan daging, aduk rata dan tambahkan air.',
      'Bumbui dengan garam, gula, dan kaldu bubuk. Aduk-aduk, masak hingga matang dan daging empuk.',
      'Tes rasa dan matikan kompor. Sajikan rawon hangat dengan taburan kecambah, telur asin dan sambal.',
    ],
    imageAsset: 'images/main/main2.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Lempah Kuning',
    star: '4.9/5',
    time: '0.75 hour',
    category: 'Makanan Utama, Indonesia',
    author: 'Eunice Euston',
    servings: '4',
    ingredients: [
      '1 kg ikan baronang , cuci bersih, balurkan air jeruk nipis, diamkan 15 menit, lalu bilas bersih',
      '1 buah nanas, kupas kulitnya lalu potong-potong',
      '5 biji rawit merah, potong-potong',
      '10 siung bamer',
      '1/4 ruas lengkuas',
      '1 ruas kunyit',
      '2 batang serai',
      '5 biji cabai merah keriting',
      '5 cabai rawit merah',
      '3 butir kemiri',
      '1 sdt terasi panggang',
      '5 lembar daun jeruk',
      'Garam, gula, penyedap jamur secukupnya',
      'Air secukupnya (hingga menutupi permukaan ikan)',
    ],
    instructions: [
      'Masukkan air secukupnya, tunggu sampai mendidih',
      'Lalu masukkan bumbu yang sudah dihaluskan dan daun jeruk.',
      'Masak sampai mendidih lagi dan keluar wangi bumbunya.',
      'Lalu masukkan ikan, nanas , cabai potong, garam, gula, dan penyedap rasa.',
      'Masak sampai ikan sampai matang lalu angkat dan sajikan.',
    ],
    imageAsset: 'images/main/main3.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Soto Padang',
    star: '4.3/5',
    time: '0.5 hour',
    category: 'Makanan Utama, Indonesia',
    author: 'Arinda Z',
    servings: '4',
    ingredients: [
      '500 gram daging sapi (campur dengan tulang supaya kaldunya lebih kerasa).',
      '2 liter air.',
      'Minyak goreng untuk menumis.',
      '2 batang sereh digeprek.',
      '3 lembar daun salam.',
      '4 lembar daun jeruk.',
      '5 buah kapulaga.',
      '8 kelopak bunga lawang.',
      '5 buah cengkeh.',
      '4 cm kayu manis.',
      '2 batang daun bawang diiris.',
      '10 siung bawang putih.',
      '6 buah bawang merah.',
      '3 ruas lengkuas.',
      '2 ruas jahe.',
      '1 ruas kunyi.',
      '1 sdt pala bubuk.',
      '1 sdm ketumbar bubuk.',
      '2 sdt lada bubuk.',
      'Garam.',
      'Sohun siram dengan air panas, rendam sebentar, angkat dan tiriskan.',
      'Perkedel kentang.',
      'kerupuk merah, sambal, seledri diiris halus, bawang goren, kecap, cuka.',
    ],
    instructions: [
      'Rebus daging sampai mendidih keluar buihnya, buah buih yang mengapung, masukkan semua bahan cemplung, lanjutkan merebus sampai daging empuk, masukan daun bawang, tunggu layu, matikan kompor, angkat daging, dan tunggu dingin.',
      'Panaskan minyak goreng, tumis bumbu halus sampai wangi, campur bumbu yang sudah ditumis ke dalam air rebusan daging, masak sebentar sampai bumbu dan kaldu menyatu. koreksi rasa.',
      'Iris tipis daging yang sudah direbus, kemudian goreng sampai garing.',
      'Tata sohun, daging didalam mangkok, siram dengan kuah soto, beri kerupuk, perkedel, seledri dan sambal. Sajikan',
    ],
    imageAsset: 'images/main/main4.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Nasi Goreng Kampung',
    star: '4/5 ',
    time: '0.5 jam',
    category: 'Makanan Utama, Indonesia',
    author: 'Adelia Rosalinda',
    servings: '4',
    ingredients: [
      '1 bonggol kembang kol ukuran sedang, cuci dan parut halus',
      '5 buah bakso sapi, potong-potong',
      '4 siung bawang putih, potong halus',
      '1 buah wortel, iris panjang tipis',
      '1 batang daun bawang, potong sesuai selera',
      '1 butir telur ayam',
      '5 buah cabai rawit merah, potong halus',
      'Secukupnya garam, penyedap rasa, dan merica',
    ],
    instructions: [
      'Panaskan wajan dan beri minyak sedikit saja. Lalu, tumis kembang kol sebentar hanya untuk mengurangi kadar air. Sisihkan.',
      'Panaskan wajan kembali dan beri sedikit minyak. Buat orak arik telur.',
      'Masukkan wortel dan bakso. Tumis sampai layu.',
      'Tambahkan bawang putih dan cabai rawit merah yang sudah dihaluskan. Aduk rata sampai matang.',
      'Masukkan kembang kol. Aduk rata. Tambahkan garam, merica, dan penyedap rasa. Terakhir, masukkan irisan daun bawang. Aduk rata. Tes rasa. Angkat dan sajikan selagi hangat.',
    ],
    imageAsset: 'images/main/main5.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Rendang Daging Padang',
    star: '4.8/5',
    time: '1 hour',
    category: 'Makanan Utama, Indonesia',
    author: 'Dreamstime.com',
    servings: '4',
    ingredients: [
      '500 gram daging sapi, potong kotak jadi 8 atau 10 bagian',
      '600 ml santan kental, dari satu setengah butir kelapa',
      '5 sdm minyak goreng',
      '300 ml air',
      '10 buah cabai merah iris',
      '6 butir bawang merah',
      '3 cm kunyit',
      '3 cm jahe',
      '3 cm lengkuas',
      '1 sdm garam',
      '2 lembar daun kunyit',
      '1 batang serai',
      '2 butir asam kandis',
    ],
    instructions: [
      'Tumis bumbu hingga harum, masukkan daging, aduk hingga berubah warna',
      'Masukkan daun kunyit, serai, dan asam kandis. Aduk perlahan',
      'Masukkan air. Masak hingga air menyusut. Aduk perlahan sesekali',
      'Masukkan santan, masak dengan api sedang',
      'Biarkan hingga daging empuk, kuah kering, dan berminyak. Angkat, sajikan.',
    ],
    imageAsset: 'images/main/main6.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Sate Ayam Madura',
    star: '4.5/5',
    time: '1 hour',
    category: 'Makanan Utama, Indonesia',
    author: 'Dreamstime.com',
    servings: '4',
    ingredients: [
      '250 g fillet ayam, dipotong dadu, kemudian tusukan ke tusukan sate',
      '1 buah jeruk nipis yang telah iris',
      '100 ml minyak goreng',
      '3 butir bawang merah, diiris tipis',
      '5 sdm kecap manis',
      'Nasi putih atau bisa diganting lontong secukupnya',
      '3 butir bawang putih',
      '4 butir bawang merah',
      '100 g kacang tanah, digoreng',
      '2 butir kemiri',
      'garam secukupnya',
      '150 ml air kaldu ayam',
      '2 sdm minyak goreng',
      'cabe merah kecil 15 buah',
      'bawang putih 4 siung',
      'garam secukupnya',
      'minyak goreng secukupnya',
    ],
    instructions: [
      'Pembuatan bumbu kacang, haluskan bawang putih,bawang merah, kacang tanah, garam, dan juga kemiri. Tumis bumbu kacang hingga tercium bau harum, kemudian masukkan air kaldu dan selanjutnya masak sampai mengental lalu angkat. Sisihkan',
      'Selanjutnya, campurkan 2 sendok makan bumbu kacang dengan ditambah 2 sendok makan kecap manis, lalu celupkan sate, terus bakar hingga setengah matang. Angkat lalu gulingkan lagi dalam bumbu, terus bakar lagi hingga matang, angkat.',
      'Untuk sambal bawang, Tumis bawang putih sampai setengah matang lalu angkat. Selanjutnya campur bawang putih ditambah juga cabe merah kecil dan garam, haluskan.',
    ],
    imageAsset: 'images/main/main7.jpg',
    saved: false,
  ),
];

var resepNoodle = [
  ResepMenu(
    name: 'Mie Aceh',
    star: '4.7/5',
    time: '0.25 hour',
    category: 'Mie',
    author: 'Laukpauk.id',
    servings: '4',
    ingredients: [
      '400 gram mie basah / kuning',
      '150 gram daging kambing / sapi, potong dadu',
      '1 batang daun bawang, iris halus.',
      '1 buah tomat, potong dadu',
      '1 sdm seledri, iris halus.',
      '1 sdt cuka',
      '100 gram kol, iris tipis.',
      '150 gram udang basah, bersihkan, buang kulitnya.',
      '2 sdm kecap manis',
      '2 sdt garam.',
      '3 sdm makan minyak goring.',
      '3 siung bawang merah, iris tipis.',
      '4 siung bawang putih, iris tipis.',
      '60 gram tauge, siangi, buang buntutnya.',
      '750 ml kaldu sapi',
      '1/2 sdt bubuk kunyit.',
      '1 sdt jinten, sangrai.',
      '1 sdt lada butir.',
      '3 siung bawang putih.',
      '4 buah cabai merah, buang bijinya.',
      '4 butir kapulaga.',
      '5 buah bawang merah.',
      'Emping goreng.',
      'Acar mentimun.',
    ],
    instructions: [
      'Tumis irisan bawang merah, irisan bawang putih dan bumbu halus hingga harum.',
      'Masukkan daging kambing / sapi, aduk. Masak hingga berubah warna.',
      'Tambahkan udang dan tomat, aduk rata.',
      'Masukkan kaldu, seledri, daun bawang, garam dan cuka.',
      'Masak hingga daging matang dan air berkurang sambil sesekali diaduk.',
      'Masukkan kol dan tauge, aduk rata. Masukkan mie dan kecap manis. Aduk rata.',
      'Sajikan dengan acar mentimun dan emping.',
    ],
    imageAsset: 'images/noodle/noodle1.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Bakmi Jawa',
    star: '3.8/5',
    time: '0.25 hour',
    category: 'Mie',
    author: 'Momrtssadailyfood',
    servings: '4',
    ingredients: [
      '1 papan mie kuning',
      '1 butir telur, kocok lepas',
      '1/2 sdt merica, haluskan',
      '2 butir kemiri',
      '2 sdm kecap manis',
      '2 siung bawang merah',
      '2 siung bawang putih',
      '4 buah cabai rawit, potong tipis',
      'Daun bawang, iris tipis',
      'Garam dan gula secukupnya',
      'Kol secukupnya, iris tipis',
    ],
    instructions: [
      'Rebus mie kuning hingga empuk, tiriskan. Goreng telur orak-arik, sisihkan.',
      'Tumis bumbu bawang putih dan bawang merah yang sudah dihaluskan hingga harum, masukkan kol, cabai rawit dan daun bawang, tumis hingga layu.',
      'Masukkan kecap manis, garam dan merica secukupnya.',
      'Masukkan mie kuning dan aduk rata.',
    ],
    imageAsset: 'images/noodle/noodle2.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Mie Ongklok Wonosobo',
    star: '3.9/5',
    time: '0.5 hour',
    category: 'Mie',
    author: 'Gus Alief',
    servings: '4',
    ingredients: [
      '200 gr mie kuning, rebus sebentar, tiriskan',
      '1 sdm tepung maizena, larutkan dengan air',
      '2 sdm kecap manis',
      '50 gr kol 1 sdm saus tiram',
      '500 ml kaldu sapi, 2 batang daun bawang, iris tipis',
      'Minyak goreng secukupnya',
      '1 sdm ebi kering',
      '1/4 sdt merica bubuk',
      '3 siung bawang merah',
      '3 siung bawang putih',
      'Garam dan gula secukupnya',
    ],
    instructions: [
      'Tumis bumbu halus hingga harum, masukkan sasu tiram dan kecap manis, aduk rata.',
      'Tuang kaldu sapi dan maska hingga mendidih. Tambahkan gula garam secukupnya dan tuang larutan maizena. Aduk hingga mengental.',
      'Tata mie dan kol di mangkuk, tuang dengan kuah kaldu dan taburi dengan daun bawang dan bawang goreng.',
    ],
    imageAsset: 'images/noodle/noodle3.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Mie Kocok Bandung',
    star: '4.6/5',
    time: '0.5 hour',
    category: 'Mie',
    author: 'Isna Sutanto',
    servings: '4',
    ingredients: [
      '1 bungkus mie telor (kurang lebih 250 gr)',
      '1 batang serai, memarkan',
      '1 cm jahe, memarkan',
      '2 lembar daun jeruk, buang tulang daunnya',
      '2 lembar daun salam',
      'Bakso secukupnya',
      'Daun bawang secukupnya, potong tipis',
      'Tauge rebus secukupnya',
      '1 sdm ebi kering',
      '1 sdt gula',
      '1/2 sdt merica',
      '2 butir kemiri',
      '4 siung bawang putih',
      '6 siung bawang merah',
      'Garam secukupnya',
      '300 gr kikil sapi/ daging tetelan sapi',
      '1.5 liter air',
      '2 siung bawang putih, memarkan',
      'Merica dan garam secukupnya',
    ],
    instructions: [
      'Rebus kikil sapi, buang busanya. Masukkan garam, bawang putih, dan merica secukupnya. Masak hingga matang, kikil empuk.',
      'Tumis bumbu halus, masukkan daun salam, serai, jahe dan daun jeruk. Masak hingga matang. Tuangkan ke dalam kaldu sapi. Rebus hingga kaldu terasa sedap.',
      'Rebus mie telur. Sisihkan.',
      'Tata dalam mangkuk, mie telur, bakso, tauge, dan potongan tomat.',
      'Potong-potong kikil sapi, taruh juga di mangkuk. Tuang dengan kuah kaldu sapi.',
      'Taburi dengan daun bawang dan bawang goreng. Sajikan.',
    ],
    imageAsset: 'images/noodle/noodle4.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Mie Titi Makassar',
    star: '4/5',
    time: '0.25 hour',
    category: 'Mie',
    author: 'Dapoer Ayu',
    servings: '4',
    ingredients: [
      '200 gr mie kuning basah/ mie kuning kering',
      '100 gr dada ayam, potong dadu kecil',
      '2 buah sosis',
      '2 buah bakso sapi, potong-potong',
      '1 butir telur, kocok lepas',
      'Sawi hijau secukupnya',
      '2 siung bawang putih, haluskan',
      '2 sdm tepung maizena, larutkan dengan air secukupnya',
      'Garam, gula pasir dan merica bubuk secukupnya',
      'Minyak goreng',
    ],
    instructions: [
      'Rendam mie dengan air panas selama 3 menit. Tiriskan dan goreng hingga kering. Sisihkan.',
      'Rebus dada ayam, ankat dada ayam dan gunakan kaldunya untuk kuah.',
      'Tumis bawang putih hingga harum, tuang air kaldu, masak hingga mendidih. Masukkan sosis, bakso dan sawi. Masak hingga sawi layu.',
      'Masukkan bumbu garam, gula dan merica secukupnya, aduk rata. Kocok telur dan tuang ke dalam kuah, aduk rata.',
      'Masukkan dada ayam. Masak hingga mendidih. Koreksi rasa.',
      'Tuang larutan maizena. Aduk rata hingga kuah mengental. Angkat.',
    ],
    imageAsset: 'images/noodle/noodle5.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Mie Cakalang Manado',
    star: '4.1/5',
    time: '0.25 hour',
    category: 'Mie',
    author: 'My Daily Journey',
    servings: '4',
    ingredients: [
      '250 gr mie telur',
      '200 gr ikan cakalang, kukus dan suwir-suwir',
      '2 batang daun bawang, potong kecil',
      'Minyak goreng secukupnya',
      'Sawi hijau secukupnya, potong-potong',
      '1 liter air',
      '1/2 sdt merica bubuk',
      '4 siung bawang putih, cincang',
      'Minyak untuk menumis',
      '1 sdm cuka makan',
      '1 sdt garam',
      '1 siung bawang putih',
      '10 buah cabai rawit/ sesuai selera',
      '3 sdm air kaldu cakalang',
    ],
    instructions: [
      'Rebus mie telur hingga matang, tiriskan dan campur dengan 2 sdm minyak agar tidak lengket. Sisihkan.',
      'Tumis bawang putih dan daun bawang hingga harum. Masukkan sawi, tumis hingga agak layu. Masukkan ikan cakalang suwir, garam dan merica, aduk rata dan tumis sebentar.',
      'Tuang air secukupnya ke dalam bumbu tumis dan masak hingga mendidih. Angkat dan sisihkan kaldu cakalang.',
      'Untuk sambalnya, haluskan bawang putih dan cabai, tambahkan cuka dan kaldu cakalang panas.',
      'Tata mie dalam mangkuk, siram dengan kuah kaldu cakalang panas, tambahkan sambal sesuai selera.',
    ],
    imageAsset: 'images/noodle/noodle6.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Mie Cakalang Manado',
    star: '4.1/5',
    time: '0.25 hour',
    category: 'Mie',
    author: 'My Daily Journey',
    servings: '4',
    ingredients: [
      '1 bungkus kwetiau basah',
      '2 butir telur ayam, orak arik',
      '1/2 sdt garam',
      '100 gram tauge',
      '150 gram daging ayam, potong dadu',
      '2 sdm kecap asin',
      '2 sdm kecap ikan',
      '2 sdm minyak wijen',
      '3 sdm kecap manis',
      '3 sdm saus tiram',
      '5 bonggol pakcoy, potong',
      '5 siung bawang putih, geprek dan cincang halus',
      'Minyak goreng untuk menumis',
    ],
    instructions: [
      'Tumis bawang putih hingga harum dengan api kecil.',
      'Masukkan daging ayam dan tumis sampai berubah warna.',
      'Tambahkan telur orak-arik dan aduk rata.',
      'Masukkan semua bumbu satu persatu dan aduk rata.',
      'Masukkan sayuran, masak sampai sedikit layu baru tambahkan kwetiau. Aduk rata dan koreksi rasa. Angkat dan sajikan.',
    ],
    imageAsset: 'images/noodle/noodle7.jpg',
    saved: false,
  ),
];

var resepDrink = [
  ResepMenu(
    name: 'Es Lemon Tea',
    star: '4.9/5',
    time: '15 minutes',
    category: 'Minuman',
    author: 'Bukkador',
    servings: '4',
    ingredients: [
      'Es batu',
      'Madu/ gula',
      'Air es',
      'Lemon',
      'Teh merk favorit Anda',
    ],
    instructions: [
      'Seduh teh dalam air panas  hingga mencapai tingkat kekentalan yang Anda inginkan. Setelah itu, Anda bisa menyisihkannya terlebih dahulu.',
      'Tuang teh ke dalam gelas dan masukan gula.',
      'Tambahkan es dan perasan air lemon. Anda sudah bisa menyajikannya dalam keadaan dingin agar lebih nikmat.',
    ],
    imageAsset: 'images/drink/drink1.png',
    saved: false,
  ),
  ResepMenu(
    name: 'Es Buah Pelangi',
    star: '4.6/5',
    time: '0.5 hour',
    category: 'Dessert',
    author: 'Aniktriwina',
    servings: '4',
    ingredients: [
      '4 buah alpukat',
      '2 buah mangga',
      'Jelly strawberry',
      'Jelly degan',
      'Krimer kental manis',
      'Gula',
      'Air es',
      'Biji chia seed',
    ],
    instructions: [
      'Potong buah-buahan dengan ukuran kecil. Potongan ini bisa Anda sesuaikan dengan selera.',
      'Lalu, buat jelly dari bahan yang sudah jadi. Biasanya, cara memasak jelly ini cukup mudah. Anda hanya perlu mencampurkannya dengan air. Setelah jelly jadi, Anda bisa dinginkan terlebih dahulu.',
      'Bila jelly sudah siap, Anda bisa memasukkan potongan buah-buahan, air es, lalu  campurkan dengan gula dan krimer.',
      'Setelah itu, Anda sudah bisa menyajikannya di dalam mangkuk.',
    ],
    imageAsset: 'images/drink/drink2.png',
    saved: false,
  ),
  ResepMenu(
    name: 'Es Buah Suka-Suka',
    star: '4.5/5',
    time: '15 minutes',
    category: 'Minuman',
    author: 'Norita',
    servings: '2',
    ingredients: [
      'Susu uht',
      'Potongan mangga',
      '5 potongan kiwi kecil-kecil',
      '3- 5 buah anggur',
      '3-5 buah strawberry',
      'Sirup melon',
      'Es batu',
    ],
    instructions: [
      'Potong buah dengan ukuran kecil-kecil agar lebih mudah dalam menatanya.',
      'Setelah itu, siapkan teko besar untuk memasukkan semua jenis buah-buahan.',
      'Tambahkan es dan gula ke dalam teko, lalu aduk merata agar terasa lebih manis.',
      'Terakhir, Anda bisa menyajikannya dalam keadaan dingin agar lebih nikmat.',
    ],
    imageAsset: 'images/drink/drink3.png',
    saved: false,
  ),
  ResepMenu(
    name: 'Es Cincau Milo',
    star: '4.1/5',
    time: '15 minutes',
    category: 'Minuman',
    author: 'Sarwokotiti',
    servings: '2',
    ingredients: [
      '250 ml air',
      '1 sachet susu Milo bubuk',
      '1/2 sdt air jeruk songkit',
      '1 sdm susu kental manis/ krimer',
      'Gula',
      'Kolang-kaling',
      'Cincau instan',
    ],
    instructions: [
      'Rebus kolang kaling terlebih dahulu sampai terasa empuk. Jangan lupa untuk meniriskan airnya.',
      'Lalu, parut cincau sesuai selera dan masukan dalam gelas.',
      'Campurkan Milo bubuk, air jeruk, kental manis, gula, dan air jeruk songkit. Aduk kembali sampai merata dan semua bahan benar-benar tercampur.',
      'Tambahkan es, kolang kaling, dan cincau ke dalam gelas.',
      'Anda bisa menyajikan saat dingin agar lebih nikmat. ',
    ],
    imageAsset: 'images/drink/drink4.png',
    saved: false,
  ),
  ResepMenu(
    name: 'Es Buah Naga',
    star: '4.5/5',
    time: '15 minutes',
    category: 'Minuman',
    author: 'Dellasuzura',
    servings: '2',
    ingredients: [
      '500 gr buah naga',
      'Susu kental manis sesuai selera',
      '250 gr natadecoco',
      'Es batu',
    ],
    instructions: [
      'Siapkan buah naga yang sudah di potong dadu kecil.',
      'Lalu, masukan es dan susu kental manis ke dalam gelas. Anda bisa mengaduknya sampai rata',
      'Setelah itu, masukan buah naga dan nata de coco.',
      'Es buah naga nata de coco pun siap untuk Anda sajikan.',
    ],
    imageAsset: 'images/drink/drink5.png',
    saved: false,
  ),
  ResepMenu(
    name: 'Cappucino Jelly',
    star: '4.4/5',
    time: '15 minutes',
    category: 'Minuman',
    author: 'Coffe Lovers',
    servings: '2',
    ingredients: [
      '1 bungkus cappuccino drink',
      '1 bungkus susu kental manis (SKM) putih ',
      'Jelly capucino',
      '500 liter air',
      'Es batu',
    ],
    instructions: [
      'Masak jelly capucino dengan 600 ml air dan masukan ke dalam wadah. Setelah sudah dingin, Anda bisa memotongnya kecil-kecil atau menyerutnya.',
      'Seduh cappucino dengan air dan berikan campuran kental manis serta air. Aduk rata.',
      'Masukkan potongan jelly ke dalam gelas, tambahkan es dan cappuccino.',
      'Letakkan dalam kulkas, dan disajikan saat dingin',
    ],
    imageAsset: 'images/drink/drink6.png',
    saved: false,
  ),
  ResepMenu(
    name: 'Es Timun Serut',
    star: '4.5/5',
    time: '15 minutes',
    category: 'Minuman',
    author: 'Dellasuzura',
    servings: '2',
    ingredients: [
      '3 timun',
      '500 gram nata de coco',
      '4 sdm selasih',
      'Sirup rasa melon',
      '3-4 buah air jeruk kunci atau lemon',
      '300 ml air matang',
      'Es batu secukupnya',
    ],
    instructions: [
      'Masukan timun serut, yang sudah Anda cuci bersih tanpa biji, dan nata de coco ke dalam gelas.',
      'Tuang air dan masukkan sedikit sirup, lalu campur sampai merata.',
      'Tambahkan juga jeruk kunci atau lemon agar terasa segar.',
      'Terakhir, Anda bisa memasukkan es batu secukupnya agar lebih dingin.',
    ],
    imageAsset: 'images/drink/drink7.png',
    saved: false,
  ),
];

var resepDessert = [
  ResepMenu(
    name: 'Jamur Crispy',
    star: '4.7/5',
    time: '20 minutes',
    category: 'Cemilan',
    author: 'Dhora Kusumadewi',
    servings: '4',
    ingredients: [
      '200 gr jamur enoki, buang bagian bawahnya, pisahkan',
      '175 gr tepung terigu serbaguna',
      '75 gr maizena',
      '1 sdt garam',
      '1 sdt baking powder',
      '1/2 sdt merica bubuk',
      '2 telur',
      '50 ml air es',
      'Minyak goreng untuk menggoreng',
    ],
    instructions: [
      'Campur terigu, maizena, garam, merica bubuk, dan baking powder. Aduk rata.',
      'Kemudian kocok lepas telur, masukkan air es, aduk rata lalu celupkan jamur. Kemudian masukkan jamur ke campuran tepung sambil diaduk agar menempel.',
      'Goreng di minyak yang sudah dipanaskan hingga matang dan kecokelatan.',
    ],
    imageAsset: 'images/dessert/dessert1.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Cilok Telur Puyuh',
    star: '4.5/5',
    time: '25 minutes',
    category: 'Cemilan',
    author: 'Norita Foods',
    servings: '8',
    ingredients: [
      '20 butir telur puyuh',
      '150 gram tepung terigu',
      '150 gram tepung tapioka',
      'Daun bawang, iris-iris',
      '200 ml air hangat',
      '2 siung bawang putih',
      'Garam secukupnya',
      'Kaldu bubuk ayam secukupnya',
    ],
    instructions: [
      'Campur tepung terigu, tapioka, bawang putih, garam, kaldu ayam, dan daun bawang. Aduk rata.',
      'Lalu tuang air hangat, uleni sampai kalis. Kemudian bentuk adonan bulat, masukkan telur puyuh di dalamnya.',
      'Terakhir didihkan air panas beri sedikit minyak supaya tidak lengket. Masukkan cilok tunggu sampai mengapung. Angkat dan tiriskan.',
    ],
    imageAsset: 'images/dessert/dessert2.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Pangsit Tahu Goreng',
    star: '4.8/5',
    time: '20 minutes',
    category: 'Cemilan',
    author: 'Pawon Karima',
    servings: '10',
    ingredients: [
      'Kulit pangsit (bagi jadi 4)',
      '200 gram tahu putih',
      '100 gram tepung tapioka',
      '0,5-1 batang daun bawang iris halus',
      '2 siung bawang putih',
      '1 siung bawang merah goreng ukuran besar',
      '1/4 sdt garam',
      '1/4 sdt merica bubuk',
      '1/2 sdt kaldu bubuk',
    ],
    instructions: [
      'Haluskan bawang putih dan bawang merah goreng. Sisihkan.',
      'Haluskan tahu. Campur dengan bumbu bawang halus, garam, merica bubuk, kaldu bubuk, dan irisan daun bawang.',
      'Masukkan tepung tapioka, uleni sampai kalis.',
      'Ambil kulit pangsit, beri isian lalu bentuk sesuai selera.',
      'Goreng pangsit tahu sampai matang.',
    ],
    imageAsset: 'images/dessert/dessert3.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Sosis Mie Gulung',
    star: '4.5/5',
    time: '20 minutes',
    category: 'Cemilan',
    author: 'Suratiwawu',
    servings: '5',
    ingredients: [
      '5 pcs sosis sapi',
      '1 bungkus mie instan goreng jumbo',
      '1 butir telur',
      'Minyak goreng secukupnya',
    ],
    instructions: [
      'Potong sosis menjadi dua bagian, sisihkan.',
      'Kemudian rebus mi instan goreng, angkat dan sisihkan.',
      'Lalu kocok lepas telur, tambahkan bumbu mie instan, kecap, minyak, dan saus.',
      'Baru masukkan mi yang sudah direbus ke kocokan telur.',
      'Kemudian gulung mi ke sosis, lalu goreng hingga berwarna keemasan. Angkat dan sajikan.',
    ],
    imageAsset: 'images/dessert/dessert4.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Balado Bakso Pedas',
    star: '4.9/5',
    time: '25 minutes',
    category: 'Cemilan',
    author: 'Dhiahoddie',
    servings: '3',
    ingredients: [
      'Bakso sapi/ayam secukupnya, goreng setengah kering',
      '3 lembar daun jeruk',
      '1 ruas lengkuas',
      'Gula, garam dan kaldu bubuk',
      '7 siung bawang merah',
      '6 siung bawang putih',
      '15 buah cabai rawit',
      '3 buah cabai merah',
      '1 buah tomat',
    ],
    instructions: [
      'Tumis bumbu halus, daun jeruk dan lengkuas sampai harum, kemudian masukkan bakso.',
      'Aduk rata dan tambahkan air secukupnya.',
      'Beri gula, garam dan kaldu bubuk, masak sampai air menyusut dan bumbu meresap. Tes rasa, angkat, dan sajikan.',
    ],
    imageAsset: 'images/dessert/dessert5.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Sandwich Goreng',
    star: '4.8/5',
    time: '30 minutes',
    category: 'Cemilan',
    author: 'Dhora Kusumadewi',
    servings: '4',
    ingredients: [
      '6 lembar roti tawar tanpa pinggiran',
      '80 gr kornet sapi',
      '2 lembar keju slice',
      '2 butir telur, kocok lepas',
      '1 sdm mentega untuk olesan',
      '50 gr mentega untuk menggoreng',
    ],
    instructions: [
      'Oleskan mentega pada roti, lalu tambahkan kornet sapi.',
      'Tutup dengan selembar roti, kemudian olesi dengan mentega dan tambahkan kornet serta keju slice. Lalu tutup lagi dengan selembar roti.',
      'Celupkan roti lapis ke dalam telur yang telah dikocok.',
      'Panaskan wajan, lalu goreng roti hingga berwarna kecokelatan.',
    ],
    imageAsset: 'images/dessert/dessert6.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Choco Brownies Pudding',
    star: '4.1/5',
    time: '1 hour',
    category: 'Dessert',
    author: 'Firamasak',
    servings: '4',
    ingredients: [
      'Susu cokelat (1.5 liter)',
      'Roti tawar (4 lembar)',
      'Nutrijel cokelat (50g)',
      'Agar-agar plain (1 bungkus)',
      'Cokelat masak/dark chocolate (100gr)',
      'Gula pasir (1/2 cup)',
      'Curshed Almond',
      'Dark Chocolate Slices',
    ],
    instructions: [
      'Blender roti, 1/2 karton susu, gula, nutrijel, agar-agar.',
      'Masukkan hasil blend ke dalam pan, panaskan dengan api sedang',
      'Masukkan susu 1/2 karton sisanya',
      'Masukkan cokelat masak/dark chocolate',
      'Tunggu sampai adonan meletup-letup',
      'Masukkan segera ke dalam cetakan, biarkan sedikit dingin',
      'Masukkan freezer, sajikan'
    ],
    imageAsset: 'images/dessert/dessert7.jpg',
    saved: false,
  ),
];

var resepCake = [
  ResepMenu(
    name: 'Putri Salju Keju',
    star: '4.5/5',
    time: '1 hour',
    category: 'Kue Lebaran',
    author: 'Iinhermayanti',
    servings: '1 kg',
    ingredients: [
      '300 gr butter (mix butter dan margarin)',
      '125 gr gula pasir halus',
      '3 kuning telur',
      '400 gr tepung terigu',
      '100 gr maizena',
      '40 gr susu bubuk full cream',
      '100 gr keju cheddar / edam',
      'Gula halus/gula donat',
    ],
    instructions: [
      'Kocok butter, gula pasir halus dan kuning telur dengan mixer kecepatan rendah, asal tercampur rata sebentar.',
      'Masukkan keju parut, aduk hingga rata.',
      'Masukkan campuran terigu, maizena dan susu bubuk. Aduk rata menggunakan sendok kayu.',
      'Gilas adonan dan cetak sesuai selera dan tata di loyang yang sudah dialasi silpat atau dioles tipis margarin.',
      'Panggang dengan suhu 140 derajat Celcius hingga matang dan berwarna kecoklatan, cukup hingga permukaannya kokoh dan kering.',
      'Ketukkan loyang hingga putri salju bisa terlepas.',
      'Saat hangat gulingkan ke dalam gula halus hingga rata kemudian gulingkan ke dalam gula donat.',
      'Tata di toples',
    ],
    imageAsset: 'images/cake/cake1.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Sabit Chocolate',
    star: '4.6/5',
    time: '1 hour',
    category: 'Kue Lebaran',
    author: 'Aisyahdiyo',
    servings: '1 kg',
    ingredients: [
      '200 gram butter',
      '175 gram margarin',
      '170 gram gula halus',
      '2 kuning telur',
      '1/4 sdt garam',
      '230 gram kacang mede, sangrai (blender)',
      '655 gram tepung protein rendah',
      'Dark chocolate / cokelat block ( dilelehakan )',
      'Flake white Chocolate',
    ],
    instructions: [
      'Siapkan bowl besar, masukan butter, margarin, gula halus dan kuning telur. Mixer sebentar saja, asal tercampur rata. (Sekitar 20-30 detik)',
      'Masukan kacang mede, mixer speed rendah sampai tercampur rata. Matikan mixer.',
      'Masukan tepung terigu, sambil diaduk dengan spatula. Lakukan sampai adonan tercampur rata.',
      'Siapkan meja kerja, plastik bening cukup besar ukurannya (untuk menggilas adonan) dan rolling pin.',
      'Ambil adonan secukupnya, letakan di plastik bening, lalu tutup lagi dengan plastik. Gilas melebar dengan rolling pin, ketebalan sedang (tidak terlalu tipis dan terlalu tebal) ratakan. Cetak dengan cookies cutter bentuk sabit, letakan diloyang beroles margarin, lakukan sampai habis.',
      'Panaskan oven suhu 150 C Oven cookies selama 20-25 menit, atau sampai matang agak kecokelatan tipis. Angkat, lalu dinginkan',
      'Setelah dingin, celupkan cookies sabit ke cokelat leleh setengahnya, lalu letakan di loyang.',
      'Tabur flake coklat, lakukan semuanya sampai habis. Lalu masukan toples.',
      'Cookies siap di sajikan untuk menyambut lebaran.',
    ],
    imageAsset: 'images/cake/cake2.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Cheese Hokaido Egg Tart',
    star: '4.7/5',
    time: '1 hour',
    category: 'Kue Lebaran',
    author: 'Resep.kuebolu',
    servings: '1 kg',
    ingredients: [
      '100 gr ( margarine + butter 50:50 )',
      '50 gr gula halus',
      '1 kuning telur',
      '20 gr susu bubuk',
      '210 gr terigu protein sedang',
    ],
    instructions: [
      'Kocok margarin, butter, gula halus dan kuning telur kurang lebih 2-3 menit.',
      'Lalu masukkan susu bubuk dan tepung. Aduk rata.',
      'Siapkan cetakan pie, diameter 5 cm, olesi dengan margarine.',
      'Ambil adonan pie kurang lebih 25gr, cetak pada cetakan pie, tusuk-tusuk pada bagian dasar pie menggunakan garpu.',
      'Panggang menggunakan oven dengan suhu 170C api atas bawah, sampai 80 persen matang sekitar 20 menit.',
      'Angkat, dinginkan.',
      'Lepas pie dari cetakan.',
      'Siap di isi dengan isian cheese tart.',
    ],
    imageAsset: 'images/cake/cake3.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Semprit Matcha',
    star: '4.8/5',
    time: '1 hour',
    category: 'Kue Lebaran',
    author: 'Trieahryntii',
    servings: '1 kg',
    ingredients: [
      '200gr tepung terigu(20sdm)',
      '100gr SKM (susu kental manis)',
      '100gr mentega(10sdm)',
      '1 bungkus chocolatos Matcha',
      'chocochips sesuai selera',
    ],
    instructions: [
      'Masukkan SKM, mentega, bubuk chocolatos Matcha dan tepung terigu (diayak). Uleni dengan tangan.',
      'Campurkan merata, sampai bisa dibentuk.',
      'Ambil tempat lalu baluri mentega, cetak adonan dengan cetakkan khusus untuk kue semprit, lalu beri tengahnya dengan Chocochips',
      'Panaskan oven, dan panggang selama 40 menit dengan api sedang atau sesuai oven.',
      'Tunggu dingin dan sajikan.',
    ],
    imageAsset: 'images/cake/cake4.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Kue Kering Nougat',
    star: '4.2/5',
    time: '1 hour',
    category: 'Kue Lebaran',
    author: 'Bunbun_fafa',
    servings: '1 kg',
    ingredients: [
      '100 gr butter',
      '100 gr margarin',
      '60 gr gula halus',
      '2 btr kuning telur',
      '250 gr tepung terigu serbaguna',
      '35 gr maizena',
      '30 gr susu bubuk',
      '1/2 sdt baking powder',
      '500 gr kacang tanah kupas, sangrai, cincang kasar',
      '500 gr gula pasir',
    ],
    instructions: [
      'Mixer butter, margarin dan gula hingga lembut, kemudian masukkan telur, kocok sampai tercampur rata.',
      'Tambahkan dengan cara diayak diatasnya tepung terigu, maizena, susu bubuk dan baking powder sedikit demi sedikit sambil di aduk menggunakan spatula.',
      'Bentuk adonan bulat lonjong.',
      'Panggang dalam oven dengan suhu 180C selama kurang lebih 20 menit atau sampai matang.',
      'Keluarkan dari oven dan biarkan dingin.',
      'Buat karamel dengan memasukkan gula pasir sedikit demi sedikit dalam wajan sampai gula mencair, kecilkan api sekecil mungkin.',
      'Ambil kue celupkan ke dalam karamel lalu gulingkan ke dalam kacang cincang dengan cepat sambil di tekan-tekan. Lakukan sampai habis.',
    ],
    imageAsset: 'images/cake/cake5.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Kuping Gajah',
    star: '4.7/5',
    time: '1/2 hour',
    category: 'Kue Lebaran',
    author: 'Pendhina.as',
    servings: '1 kg',
    ingredients: [
      '250 gram tepung terigu protein rendah atau sedang',
      '1 butir telur',
      '80 gram gula halus',
      '1/4 sdt garam',
      '1/4 sdt vanilli',
      'Santan instan 1 bungkus kecil',
      '1 sdm margarin',
      '1-2 sdt coklat bubuk',
    ],
    instructions: [
      'Campur semua bahan kering, tambahkan margarin, telur dan santan sedikit demi sedikit, sambil di aduk rata hingga jadi adonan yang kalis dan bisa di pulung.',
      'Bagi jadi dua bagian, satu bagian tambahkan coklat bubuk secukupnya',
      'Aduk rata sambil di uleni ringan.',
      'Tipiskan kedua adonan dengan pasta engine atau rolling pin,',
      'Tumpuk, gulung dan padatkan.',
      'Simpan adonan di dalam kulkas sebentar, kira-kira 20 menit agar lebih padat dan mudah di potong',
      'Gilas kembali adonan dengan ukuran yang lebih kecil dan tipis.',
      'Goreng adonan yang sudah terbentuk bulat pipih ke dalam minyak yang sudah di panasakan dengan api kecil.',
      'Tunggu hingga kering dan renyah, angkat dan tiriskan.',
    ],
    imageAsset: 'images/cake/cake6.jpg',
    saved: false,
  ),
  ResepMenu(
    name: 'Kue Keciput',
    star: '4.3/5',
    time: '1 hour',
    category: 'Kue Lebaran',
    author: 'Mamaquink_88',
    servings: '1 kg',
    ingredients: [
      '1 butir telur',
      '1 kuning telur',
      '4 sdm gula pasir',
      '120 ml santan kental',
      '1 sdt garam',
      '200 gr tepung ketan putih',
      '1/2 sdt baking powder',
      '1/2 sdt soda kue',
      '250 gr wijen putih',
      'Minyak untuk menggoreng',
    ],
    instructions: [
      'Campur telur, kuning telur dan gula pasir. Lalu kocok selama 2 menit.',
      'Masukkan santan dan garam, aduk hingga tercampur rata.',
      'Masukkan tepung ketan yang sudah diayak bersama baking powder dan soda kue, sambil diaduk rata.',
      'Bentuk adonan menjadi bulat kecil.',
      'Gulingkan di atas wijen.',
      'Panaskan minyak, goreng adonan sampai kekuningan dan terapung di permukaan minyak.',
    ],
    imageAsset: 'images/cake/cake7.jpg',
    saved: false,
  ),
];
